### ISSUE TITLE
Can't connect to mtproto proxy

### ISSUE THREAD

**Issue by valenokk** [freefd/vpn_box#1]
Hi.
I tried following your guide, and I can't make my Telegram client to connect to MtProto proxy. 
I tried checking the log of mtg and Traefik, but they are both empty. 
Is there any way to debug the connection, right now I don't even have an idea on what's failing?

**Comment by valenokk** [comment]
Okay, finally figured it our myself.
My problem is that I didn't understand how HostSNI works. 
I host my server on AWS, so I used "amazon.com" to generate mtg secret.
However I access my server through my custom domain "mtg.myserver.com", so that's what I did put in HostSNI part of Traefik configuration.

After I changed it to "amazon.com" everything worked.

**Comment by freefd** [comment]
Dear @valenokk, sorry for such a late reply. I'm glad you managed to fix the issue on your own :)

Yes, this technique can be compared to domain fronting approach. Telegram client sends packets with SNI you selected during generating the secret, and to the 3rd party spectator the packet looks like a general packet to a service specified in the SNI. But actually the client connects to MTProto proxy instead.

This implicitly mentioned in the article:
```
labels:
  ...
  - traefik.tcp.routers.mtg.rule=HostSNI(`${MTG_TLS_HOST}`)
  - traefik.tcp.routers.mtg.tls.passthrough=true
  ...
```

Where MTG_TLS_HOST variable is defined in the .env file:

```
MTG_TLS_HOST=duckduckgo.com
```

Finally, in the Traefik we could find it as follows:
![image](https://user-images.githubusercontent.com/133116/160288933-384d58d6-fdc5-4ca0-aec3-cf78076e42c2.png)
